//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EArsivWsService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class EArsivFault
    {
        
        private string messageField;
        
        private System.Nullable<int> codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class attachment
    {
        
        private string fileNameField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class InterruptedException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", ConfigurationName="EArsivWsService.EArsivWs")]
    public interface EArsivWs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendDocumentFile", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EArsivWsService.EArsivFault), Action="urn:SendDocumentFile", Name="EArsivFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EArsivWsService.sendDocumentFileResponse> sendDocumentFileAsync(EArsivWsService.sendDocumentFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetBatchStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EArsivWsService.EArsivFault), Action="urn:GetBatchStatus", Name="EArsivFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(EArsivWsService.InterruptedException), Action="urn:GetBatchStatus", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EArsivWsService.getBatchStatusResponse> getBatchStatusAsync(EArsivWsService.getBatchStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UserListByUserType", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EArsivWsService.EArsivFault), Action="urn:UserListByUserType", Name="EArsivFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EArsivWsService.getUserListByUserTypeResponse> getUserListByUserTypeAsync(EArsivWsService.getUserListByUserType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetUserList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EArsivWsService.EArsivFault), Action="urn:GetUserList", Name="EArsivFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EArsivWsService.getUserListResponse> getUserListAsync(EArsivWsService.getUserList request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDocumentFile", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class sendDocumentFile
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.attachment Attachment;
        
        public sendDocumentFile()
        {
        }
        
        public sendDocumentFile(EArsivWsService.attachment Attachment)
        {
            this.Attachment = Attachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDocumentFileResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class sendDocumentFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendDocumentFileResponse()
        {
        }
        
        public sendDocumentFileResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class durum
    {
        
        private string durumAciklamaField;
        
        private int durumKoduField;
        
        private string paketIdField;
        
        private string tCKimlikNoField;
        
        private string vergiKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string durumAciklama
        {
            get
            {
                return this.durumAciklamaField;
            }
            set
            {
                this.durumAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int durumKodu
        {
            get
            {
                return this.durumKoduField;
            }
            set
            {
                this.durumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string paketId
        {
            get
            {
                return this.paketIdField;
            }
            set
            {
                this.paketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vergiKimlikNo
        {
            get
            {
                return this.vergiKimlikNoField;
            }
            set
            {
                this.vergiKimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBatchStatus", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getBatchStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paketId;
        
        public getBatchStatus()
        {
        }
        
        public getBatchStatus(string paketId)
        {
            this.paketId = paketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBatchStatusResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getBatchStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.durum @return;
        
        public getBatchStatusResponse()
        {
        }
        
        public getBatchStatusResponse(EArsivWsService.durum @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public enum UserType
    {
        
        /// <remarks/>
        EARSIV,
        
        /// <remarks/>
        EMUSTAHSIL,
        
        /// <remarks/>
        ESERBEST_MESLEK,
        
        /// <remarks/>
        EMRAPOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public enum UserListType
    {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        CSV,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserListByUserType", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserListByUserType
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.UserType userType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.UserListType userListType;
        
        public getUserListByUserType()
        {
        }
        
        public getUserListByUserType(EArsivWsService.UserType userType, EArsivWsService.UserListType userListType)
        {
            this.userType = userType;
            this.userListType = userListType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserListByUserTypeResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserListByUserTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.attachment @return;
        
        public getUserListByUserTypeResponse()
        {
        }
        
        public getUserListByUserTypeResponse(EArsivWsService.attachment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserList", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserList
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type;
        
        public getUserList()
        {
        }
        
        public getUserList(string type)
        {
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserListResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EArsivWsService.attachment @return;
        
        public getUserListResponse()
        {
        }
        
        public getUserListResponse(EArsivWsService.attachment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface EArsivWsChannel : EArsivWsService.EArsivWs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EArsivWsClient : System.ServiceModel.ClientBase<EArsivWsService.EArsivWs>, EArsivWsService.EArsivWs
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EArsivWsClient() : 
                base(EArsivWsClient.GetDefaultBinding(), EArsivWsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EArsivWsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EArsivWsClient(EndpointConfiguration endpointConfiguration) : 
                base(EArsivWsClient.GetBindingForEndpoint(endpointConfiguration), EArsivWsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EArsivWsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EArsivWsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EArsivWsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EArsivWsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EArsivWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EArsivWsService.sendDocumentFileResponse> EArsivWsService.EArsivWs.sendDocumentFileAsync(EArsivWsService.sendDocumentFile request)
        {
            return base.Channel.sendDocumentFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<EArsivWsService.sendDocumentFileResponse> sendDocumentFileAsync(EArsivWsService.attachment Attachment)
        {
            EArsivWsService.sendDocumentFile inValue = new EArsivWsService.sendDocumentFile();
            inValue.Attachment = Attachment;
            return ((EArsivWsService.EArsivWs)(this)).sendDocumentFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EArsivWsService.getBatchStatusResponse> EArsivWsService.EArsivWs.getBatchStatusAsync(EArsivWsService.getBatchStatus request)
        {
            return base.Channel.getBatchStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EArsivWsService.getBatchStatusResponse> getBatchStatusAsync(string paketId)
        {
            EArsivWsService.getBatchStatus inValue = new EArsivWsService.getBatchStatus();
            inValue.paketId = paketId;
            return ((EArsivWsService.EArsivWs)(this)).getBatchStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EArsivWsService.getUserListByUserTypeResponse> EArsivWsService.EArsivWs.getUserListByUserTypeAsync(EArsivWsService.getUserListByUserType request)
        {
            return base.Channel.getUserListByUserTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EArsivWsService.getUserListByUserTypeResponse> getUserListByUserTypeAsync(EArsivWsService.UserType userType, EArsivWsService.UserListType userListType)
        {
            EArsivWsService.getUserListByUserType inValue = new EArsivWsService.getUserListByUserType();
            inValue.userType = userType;
            inValue.userListType = userListType;
            return ((EArsivWsService.EArsivWs)(this)).getUserListByUserTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EArsivWsService.getUserListResponse> EArsivWsService.EArsivWs.getUserListAsync(EArsivWsService.getUserList request)
        {
            return base.Channel.getUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EArsivWsService.getUserListResponse> getUserListAsync(string type)
        {
            EArsivWsService.getUserList inValue = new EArsivWsService.getUserList();
            inValue.type = type;
            return ((EArsivWsService.EArsivWs)(this)).getUserListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EArsivWsPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EArsivWsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://test.efatura.gov.tr/earsiv/services/EArsivWsPort");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EArsivWsClient.GetBindingForEndpoint(EndpointConfiguration.EArsivWsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EArsivWsClient.GetEndpointAddress(EndpointConfiguration.EArsivWsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EArsivWsPort,
        }
    }
}
